config/routes.rb
Rails.application.routes.draw do
  resources :turmas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "turmas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/turma.rb
class Turma < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: %i[ show edit update destroy ]

  # GET /turmas or /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1 or /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas or /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to turma_url(@turma), notice: "Turma was successfully created." }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1 or /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to turma_url(@turma), notice: "Turma was successfully updated." }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1 or /turmas/1.json
  def destroy
    @turma.destroy

    respond_to do |format|
      format.html { redirect_to turmas_url, notice: "Turma was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:descricao, :estado, :curso, :instituicao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/turmas/_form.html.erb
<%= form_with(model: turma) do |form| %>
  <% if turma.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.number_field :estado %>
  </div>

  <div>
    <%= form.label :curso, style: "display: block" %>
    <%= form.text_field :curso %>
  </div>

  <div>
    <%= form.label :instituicao, style: "display: block" %>
    <%= form.text_field :instituicao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/_turma.html.erb
<div id="<%= dom_id turma %>">
  <p>
    <strong>Descricao:</strong>
    <%= turma.descricao %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= turma.estado %>
  </p>

  <p>
    <strong>Curso:</strong>
    <%= turma.curso %>
  </p>

  <p>
    <strong>Instituicao:</strong>
    <%= turma.instituicao %>
  </p>

</div>

app/views/turmas/edit.html.erb
<h1>Editing turma</h1>

<%= render "form", turma: @turma %>

<br>

<div>
  <%= link_to "Show this turma", @turma %> |
  <%= link_to "Back to turmas", turmas_path %>
</div>

app/views/turmas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Turmas</h1>

<div id="turmas">
  <% @turmas.each do |turma| %>
    <%= render turma %>
    <p>
      <%= link_to "Show this turma", turma %>
    </p>
  <% end %>
</div>

<%= link_to "New turma", new_turma_path %>

app/views/turmas/new.html.erb
<h1>New turma</h1>

<%= render "form", turma: @turma %>

<br>

<div>
  <%= link_to "Back to turmas", turmas_path %>
</div>

app/views/turmas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @turma %>

<div>
  <%= link_to "Edit this turma", edit_turma_path(@turma) %> |
  <%= link_to "Back to turmas", turmas_path %>

  <%= button_to "Destroy this turma", @turma, method: :delete %>
</div>